---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
<<<<<<< Updated upstream
  - motus ==4.0.4
=======
  - motus=4.0.4
>>>>>>> Stashed changes
