name: "cayman_profile"
description: A command-line tool for profiling CAZyme abundances in metagenomic datasets
keywords:
  - classify
  - metagenomics
  - fastq
  - functional profiling
tools:
  - "cayman":
      description: "A command-line tool for profiling CAZyme abundances in metagenomic datasets"
      tool_dev_url: "https://github.com/zellerlab/cayman"
      doi: "10.1101/2024.01.08.574624"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - input:
        type: file
        description: |
          Single or paired ended input fastq files
        ontologies: []
  - db:
      type: directory
      description: |
        required database files for cayman: GMGC10 sequences (.fna.gz), annotation file (.csv), and bwa index
        pattern: "*/"
output:
  out:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.cazy.txt.gz":
            type: file
            description: The main CAZy RPKM feature matrix at the domain level
            pattern: "*.cazy.txt.gz"
            ontologies: []
  aln_stats:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.aln_stats.txt.gz":
            type: file
            description: BWA alignment statistics
            pattern: "*.aln_stats.txt.gz"
            ontologies: []
  gene_counts:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.gene_counts.txt.gz":
            type: file
            description: The RPKM feature matrix at the gene level
            pattern: "*.gene_counts.txt.gz"
            ontologies: []
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.cayman.log":
            type: file
            description: Execution log
            pattern: "*.cayman.log"
            ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@saulpierotti"
maintainers:
  - "@saulpierotti"
